"""
Goal: take in .mp3 audio files and write a txt file with timestamps for each sentence!
Usage: python3 main.py <file_path>
"""
import os.path
import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from datasets import load_dataset
from sys import argv

file_path = argv[1]

# Error Handling
if len(argv) != 2:
    print("Improper implementation!")
    print("Usage: python3 main.py <file_path>")
    exit()

if not os.path.exists(file_path):
    print("File not found!")
    exit()

# Text file creation
striped_name = os.path.splitext(os.path.basename(file_path))[0]

transcript_file = None
if not os.path.exists(f"transcripts/{striped_name}_transcript.txt"):
    transcript_file = open(f"transcripts/{striped_name}_transcript.txt", "x+")
else:
    transcript_file = open(f"transcripts/{striped_name}_transcript.txt", "w")

# Audio processing
device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "openai/whisper-large-v3"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

"""
Consider editing pipeline to process in batches to improve speed.
Allegedly the chunked algorithm is faster than the sequential algorithm, 
but when I tested this was not the case!
"""

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    torch_dtype=torch_dtype,
    device=device,
)

# Also consider changing the dataset to a smaller dataset
dataset = load_dataset("distil-whisper/librispeech_long", "clean", split="validation")

# Timestamps are bugged which is clear if you look at textfiles generated by videos longer than 30 sec
result = pipe(file_path, return_timestamps=True)

# Consider adding logic to write accurate timestamps to the textfile

# Write to text file
for chunk in result["chunks"]:
    transcript_file.write(str(chunk["timestamp"][0]))
    transcript_file.write(": ")
    transcript_file.write(chunk["text"])
    transcript_file.write("\n")
    transcript_file.write("\n")

transcript_file.close()